defaults: &defaults
  host: localhost
  
development:
  <<: *defaults
  uri: mongodb://root:tilldawn@flame.mongohq.com:27108/tildawn-demo

test:
  host: localhost
  database: tilldawn-temp

production:
  uri: mongodb://root:tilldawn@flame.mongohq.com:27108/tildawn-demo
