defaults: &defaults
  host: localhost
  
development:
  <<: *defaults
  uri: mongodb://admin:tilldawn@flame.mongohq.com:27040/tilldawn-development

test:
  host: localhost
  database: till_dawn_test

# set these environment variables on your prod server
production:
  uri: <%=ENV['MONGOHQ_URL'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
