defaults: &defaults
  host: localhost
  
development:
  <<: *defaults
  uri: mongodb://root:password@flame.mongohq.com:27108/yenta-temp

test:
  host: localhost
  database: yenta-temp

# set these environment variables on your prod server
production:
  uri: mongodb://root:password@flame.mongohq.com:27108/yenta-temp
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
